# Numpy_Assignment_2::

In [1]:
import numpy as np

## Question:1

### Convert a 1D array to a 2D array with 2 rows?

#### Desired output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [2]:
arr1=np.arange(0,10)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
arr2=arr1.reshape(2,5)
arr2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## Question:2

###  How to stack two arrays vertically?

#### Desired Output::

In [4]:
v1=np.array([[0, 1, 2, 3, 4],[5, 6, 7, 8, 9]])
v1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [5]:
v2=np.array([[1, 1, 1, 1, 1],[1, 1, 1, 1, 1]])
v2

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [6]:
np.vstack((v1,v2))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [7]:
np.concatenate((v1,v2),axis=0)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## Question:3

### How to stack two arrays horizontally?

#### Desired Output::

In [8]:
h1=np.array([0, 1, 2, 3, 4, 1, 1, 1, 1, 1])
h1

array([0, 1, 2, 3, 4, 1, 1, 1, 1, 1])

In [9]:
h2=np.array([5, 6, 7, 8, 9, 1, 1, 1, 1, 1])
h2

array([5, 6, 7, 8, 9, 1, 1, 1, 1, 1])

In [10]:
np.vstack((h1,h2))

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [11]:
np.concatenate((h1,h2))

array([0, 1, 2, 3, 4, 1, 1, 1, 1, 1, 5, 6, 7, 8, 9, 1, 1, 1, 1, 1])

## Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::

In [12]:
arr3=np.arange(0,10).reshape(2,5)
arr3

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [13]:
flatten_arr = arr3.flatten()
flatten_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output::

In [14]:
arr4=np.arange(0,15).reshape(3,5)
arr4

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [15]:
ravel_array=np.ravel(arr4)
ravel_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

In [16]:
a3=np.arange(0,15).reshape(5,3)
a3

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

## Question:7

### Create 5x5 an array and find the square of an array?

In [17]:
arr5=np.arange(25).reshape(5,5)
arr5

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [18]:
print(f"The square of array is \n {np.power(arr5,2)}")

The square of array is 
 [[  0   1   4   9  16]
 [ 25  36  49  64  81]
 [100 121 144 169 196]
 [225 256 289 324 361]
 [400 441 484 529 576]]


## Question:8

### Create 5x6 an array and find the mean?

In [19]:
arr6=np.arange(30).reshape(5,6)
arr6

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [20]:
print(f"The mean of array is {arr6.mean()} ")

The mean of array is 14.5 


## Question:9

### Find the standard deviation of the previous array in Q8?

In [21]:
print(f"The Standard deviation of array is {arr6.std()} ")

The Standard deviation of array is 8.65544144839919 


## Question:10

### Find the median of the previous array in Q8?

In [22]:
print(f"The Median of array is {np.median(arr6)}  ")

The Median of array is 14.5  


## Question:11

### Find the transpose of the previous array in Q8?

In [23]:
print(f"The transpose of arr6 is \n {arr6.transpose()}")

The transpose of arr6 is 
 [[ 0  6 12 18 24]
 [ 1  7 13 19 25]
 [ 2  8 14 20 26]
 [ 3  9 15 21 27]
 [ 4 10 16 22 28]
 [ 5 11 17 23 29]]


## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

In [24]:
arr4=np.arange(16).reshape(4,4)
arr4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [25]:
print(f"The sum of diagonal elements of arr4 is \n {np.trace(arr4)}")

The sum of diagonal elements of arr4 is 
 30


## Question:13

### Find the determinant of the previous array in Q12?

In [26]:
print(f"The determinant of arr4 is \n {np.linalg.det(arr4)}")

The determinant of arr4 is 
 0.0


## Question:14

### Find the 5th and 95th percentile of an array?

In [27]:
arr = np.array([[10, 7, 4,78], [50,3, 2, 1]])
arr

array([[10,  7,  4, 78],
       [50,  3,  2,  1]])

In [28]:
np.percentile(arr, 5)

1.35

In [29]:
np.percentile(arr, 95)

68.19999999999999

## Question:15

### How to find if a given array has any null values?

Example 1

In [30]:
z = np.zeros(10)
z
# np.where((z==0))

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [31]:
np.isnan(z)

array([False, False, False, False, False, False, False, False, False,
       False])

In [32]:
np.isnan(z).any()

False

Example 2

In [33]:
a = np.array([np.nan, 1, 2, 3, 4, 5, 6, 8])
np.isnan(a)

array([ True, False, False, False, False, False, False, False])

In [34]:
# a = np.array([np.nan, 1, 2, 3, 4, 5, 6, 8])
np.isnan(a).any()

True