# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [1]:
import numpy as np

2. Create a null vector of size 10 

In [2]:
v1=np.zeros(10)
v1

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

3. Create a vector with values ranging from 10 to 49

In [4]:
v2=np.arange(10,50)
v2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

4. Find the shape of previous array in question 3

In [5]:
np.shape(v2)

(40,)

5. Print the type of the previous array in question 3

In [6]:
v2.dtype

dtype('int32')

6. Print the numpy version and the configuration


In [7]:
print("NumPy version is : ",  np.__version__)
# np.show_config()

NumPy version is :  1.19.4


7. Print the dimension of the array in question 3


In [8]:
v2.ndim

1

8. Create a boolean array with all the True values

In [9]:
a1 = np.ones(15, dtype="bool")
a1

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True])

9. Create a two dimensional array




In [10]:
a2 = np.arange(20).reshape((4,5))
a2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

10. Create a three dimensional array



In [11]:
a3 = np.arange(20).reshape(2,2,5)
a3

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]])

Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [12]:
v3 = [1,2,3,4,5,6,7,8,9,10]
print(f"Original vector is : {v3}")

Original vector is : [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [13]:
v3 = v3[::-1]
print(f"Reverse vector is : {v3}")

Reverse vector is : [10, 9, 8, 7, 6, 5, 4, 3, 2, 1]


12. Create a null vector of size 10 but the fifth value which is 1 

In [14]:
z = np.zeros(10)
z[4] = 1
z

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

13. Create a 3x3 identity matrix

In [15]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [17]:
#Another method:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [18]:
arr = np.array([1, 2, 3, 4, 5], dtype="float")
print(f"Array is : {arr} and datatype is now {arr.dtype}")

Array is : [1. 2. 3. 4. 5.] and datatype is now float64


15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [19]:
arr1 = np.array([[1., 2., 3.],[4., 5., 6.]])  
arr2 = np.array([[0., 4., 1.],[7., 2., 12.]])
arr1 * arr2

array([[ 0.,  8.,  3.],
       [28., 10., 72.]])

16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [20]:
arr1 = np.array([[1., 2., 3.],[4., 5., 6.]]) 
arr2 = np.array([[0., 4., 1.],[7., 2., 12.]])
arr2>arr1

array([[False,  True, False],
       [ True, False,  True]])

17. Extract all odd numbers from arr with values(0-9)

In [21]:
a4 = np.arange(0,10)
a4[1::2]

array([1, 3, 5, 7, 9])

18. Replace all odd numbers to -1 from previous array

In [22]:
a4[1::2] = -1
a4

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [23]:
a5 = np.arange(10)
a5[5:9] = 12
a5

array([ 0,  1,  2,  3,  4, 12, 12, 12, 12,  9])

20. Create a 2d array with 1 on the border and 0 inside

In [24]:
z = np.ones((4,4))
z [1:-1,1:-1] = 0
print(z)

[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [25]:
arr2d = np.array([[1, 2, 3],[4, 5, 6], [7, 8, 9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [26]:
arr2d[1,1] = 12
arr2d

array([[ 1,  2,  3],
       [ 4, 12,  6],
       [ 7,  8,  9]])

22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [27]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [28]:
arr3d[0] = 64
arr3d

array([[[64, 64, 64],
        [64, 64, 64]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [29]:
arr2d = np.arange(0,9).reshape(3,3)
arr2d

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [30]:
arr2d[0]

array([0, 1, 2])

24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [31]:
arr2d[1,1]

4

25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [32]:
arr2d[:2, 2:]

array([[2],
       [5]])

26. Create a 10x10 array with random values and find the minimum and maximum values

In [33]:
a6 = np.random.randn(10,10)
a6

array([[ 0.38938275,  0.77773401, -0.00414517,  0.10214575, -0.00722495,
        -1.36370099,  0.08045424,  1.54083787,  1.15052366, -1.75905804],
       [-1.45434962,  0.52676334, -0.11555221,  0.31541306, -1.02320016,
        -0.50289592, -1.26381498,  0.22057255,  0.96903072, -1.76740288],
       [ 0.64768716,  2.7675091 ,  0.44350433,  0.0247042 ,  1.19632448,
         1.76161814,  1.85797628,  0.23597702, -1.42401392,  1.49209869],
       [-0.85953954,  0.24016736,  0.68207338,  0.57865182, -0.46795442,
         0.21640267, -1.07724798,  0.336477  ,  0.34420683, -0.79213556],
       [ 0.1173619 ,  0.29120467, -1.19377882, -1.41640907,  1.45064091,
         2.37025809, -0.41578759, -0.32702679,  1.9231412 , -0.91398795],
       [ 0.10501537, -0.3460379 ,  0.5074523 ,  0.93060074,  0.02597183,
        -0.15853088,  1.64228157, -0.92478486,  0.98289019,  0.5673081 ],
       [-0.58533364, -0.57556773,  1.69863267, -0.77639272,  1.27314379,
        -0.12619452,  1.18986408,  0.10341244

In [34]:
# print(f" The Minimum value of array is {a6.min()} and maximum value is {a6.max()}" )
print(f" The Minimum value of array is {np.min(a6)} and Maximum value is {np.max(a6)}" )

 The Minimum value of array is -2.48646819199058 and Maximum value is 2.767509103406203


27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [35]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a,b)

array([2, 4])

28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [36]:
np.where(np.in1d(a,b))

(array([1, 3, 5, 7], dtype=int64),)

29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [37]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
data[~(names == 'Will')]
# data[names!='Will']

array([[-0.84209391, -0.18142136, -0.61290811,  1.56865635],
       [-0.37914038, -1.15918853, -1.03159991,  1.93637778],
       [-1.61495565, -2.36036783,  0.01017516, -0.20915526],
       [-0.13907405,  1.2327894 ,  1.39034132,  0.80002585],
       [-0.04910305,  3.06245269,  0.30470989, -0.63823015]])

30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



In [38]:
data[((names!='Will') & (names!='Joe'))]

array([[-0.84209391, -0.18142136, -0.61290811,  1.56865635],
       [-1.61495565, -2.36036783,  0.01017516, -0.20915526]])

Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [39]:
a7 = np.arange(1,16,dtype=np.float32).reshape(5,3)
a7

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.],
       [13., 14., 15.]], dtype=float32)

32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [40]:
a8 = np.arange(1,17,dtype=np.float32).reshape(2,2,4)
a8

array([[[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.]],

       [[ 9., 10., 11., 12.],
        [13., 14., 15., 16.]]], dtype=float32)

33. Swap axes of the array you created in Question 32

In [41]:
a8.T
# a8.swapaxes(1,2)

array([[[ 1.,  9.],
        [ 5., 13.]],

       [[ 2., 10.],
        [ 6., 14.]],

       [[ 3., 11.],
        [ 7., 15.]],

       [[ 4., 12.],
        [ 8., 16.]]], dtype=float32)

34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [42]:
a9 = np.linspace(0, 1, 10)
print(a9)
sq = np.sqrt(a9)
print(sq)
np.where(sq < 0.5 , 0 , sq)


[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]
[0.         0.33333333 0.47140452 0.57735027 0.66666667 0.74535599
 0.81649658 0.8819171  0.94280904 1.        ]


array([0.        , 0.        , 0.        , 0.57735027, 0.66666667,
       0.74535599, 0.81649658, 0.8819171 , 0.94280904, 1.        ])

35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [43]:
ar1=np.random.randn(12)
ar2=np.random.randn(12)
ar_max=np.maximum(ar1,ar2)
ar_max

array([ 0.04870274,  1.48129902,  0.21428467,  0.09013318,  2.17403239,
        0.93609518,  1.68992268,  0.79734482, -0.66315643,  2.2593848 ,
       -0.68394937,  0.5177092 ])

36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [44]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
u = np.unique(names)
print(np.sort(u))

['Bob' 'Joe' 'Will']


37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [45]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
np.setdiff1d(a,b)

array([1, 2, 3, 4])

38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


In [46]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
newColumn = np.array([[10,10,10]])
sampleArray[::,2] = newColumn
sampleArray

array([[34, 43, 10],
       [82, 22, 10],
       [53, 94, 10]])

39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [47]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])
x.dot(y)
# np.dot(x,y)

array([[ 28.,  64.],
       [ 67., 181.]])

40. Generate a matrix of 20 random values and find its cumulative sum

In [48]:
a20=np.random.randn(20)
np.cumsum(a20)

array([ 0.14224909,  0.6054715 , -0.98937896,  0.09661059,  1.00650381,
        1.95543387,  1.79503517,  2.77648164,  2.32015788,  1.55422015,
        1.1913622 ,  1.04555385,  1.98667296,  2.78748384,  4.73184152,
        5.54667146,  5.34046885,  6.45481183,  6.69597903,  5.37839533])